message: "Write shorter sentences (less than 40 words)."
link: ""
extends: occurrence
scope: sentence
level: warning
max: 40
token: \b(\w+)\b

# This catches an entire sentence and checks if its 40 character long.